version: '3.9'
services:
  database:
    image: postgres:16-alpine
    container_name: dsatracker-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  backend:
    build: ./backend
    container_name: dsatracker-api
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: dsatracker-frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8080:80
    depends_on:
      - backend

volumes:
  pgdata: