name: CD for dsatracker
on:
    push:
        branches: [main]
jobs:
    build-push:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: [frontend,backend]
        defaults:
            run:
                working-directory: ./${{ matrix.service }}
        steps:
            - uses: actions/checkout@v4
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
            - name: Build and Push Image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/dsatracker-${{ matrix.service }}:${{ github.sha }} .
                docker push ${{ secrets.DOCKER_USERNAME }}/dsatracker-${{ matrix.service }}:${{ github.sha }}
            - name: Tag as latest and push
              run: |
                docker tag ${{ secrets.DOCKER_USERNAME }}/dsatracker-${{ matrix.service }}:${{ github.sha }} ${{ secrets.DOCKER_USERNAME}}/dsatracker-${{ matrix.service }}:latest
                docker push ${{ secrets.DOCKER_USERNAME}}/dsatracker-${{ matrix.service }}:latest