name: CI for dsatracker
on:
  pull_request:
    branches: [main]
  
jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend,backend]
    defaults:
      run:
        working_directory: ./${{ matrix.service }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      
